class Globals:
    TEMPERATURE_LMIN = 5
    TEMPERATURE_LMAX = 25
    TEMPERATURE_UMIN = 65
    TEMPERATURE_UMAX = 75
    DRIFTMIN = 200
    DRIFTMAX = 350
    RISE = 5
    GROWTH_PER_MONOMER = 0.25
    GROWTH_FACTOR = 1.5
    ABSORB_RATE = 2.5
    MECHANICAL_EVENT = 0.2
    MONOMER_MOVE_RATE = 5
